[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "LeonelR033"
version = "0.0.1"
authors = [
  { name="Leonel RodrÃ­guez - Carlos Rosario", email="LeonelR03@outlook.com" },
]
description = "Kata Range, Coding Dojo in pair plan"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/LeonelRod/PairDojoKata2.git"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"