[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "umls-client"
version = "0.1.0"
authors = [
  { name="Jamie C", email="jamiesprax@gmail.com" },
]
description = "A light umls client with rate limiting"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://gitlab.com/jamiesprax/umls-client"
"Bug Tracker" = "https://gitlab.com/jamiesprax/umls-client/-/issues"