[tool.poetry]
name = "redis_admin_client"
version = "0.1.0"
description = "High level redis client"
authors = ["Kharthigeyan Satyamurthy <ksatyamurthy@groupon.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.4.3"
redis = "^4.3.4"
ray = "^1.13.0"
ipcalc = "^1.99.0"
requests = "^2.28.1"
plotly-express = "^0.4.1"
altair = "^4.2.0"
seaborn = "^0.11.2"
pandasql = "^0.7.3"
plotly = "^5.9.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
