[tool.poetry]
name = "laz"
version = "0.0.1-alpha.6"
description = "CLI tool to configure and run parameterized actions against targets."
authors = ["Josh Wycuff <Josh.Wycuff@gmail.com>"]
readme = "README.md"
packages = [{include = "laz"}]

[tool.poetry.dependencies]
python = ">=3.8,<4"
PyYAML = ">=6,<7"
Jinja2 = ">=3,<4"
poetry = "^1.1.13"

[tool.poetry.dev-dependencies]
mkdocs = "^1.3.0"
mkdocs-material = "^8.3.7"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
laz = "laz.main:main"
